Repository adjikpo/voting_app, pull requests merged in 2021-01, with the labels that each got.

#4 Feature/add symfony 5 files
  .env
  .env.test
  .gitignore
  bin/console
  bin/phpunit
  composer.json
  composer.lock
  config/bundles.php
  config/packages/cache.yaml
  config/packages/dev/debug.yaml
  config/packages/dev/monolog.yaml
  config/packages/dev/web_profiler.yaml
  config/packages/doctrine.yaml
  config/packages/doctrine_migrations.yaml
  config/packages/framework.yaml
  config/packages/mailer.yaml
  config/packages/notifier.yaml
  config/packages/prod/deprecations.yaml
  config/packages/prod/doctrine.yaml
  config/packages/prod/monolog.yaml
  config/packages/prod/routing.yaml
  config/packages/routing.yaml
  config/packages/security.yaml
  config/packages/sensio_framework_extra.yaml
  config/packages/test/framework.yaml
  config/packages/test/monolog.yaml
  config/packages/test/twig.yaml
  config/packages/test/validator.yaml
  config/packages/test/web_profiler.yaml
  config/packages/translation.yaml
  config/packages/twig.yaml
  config/packages/validator.yaml
  config/preload.php
  config/routes.yaml
  config/routes/annotations.yaml
  config/routes/dev/framework.yaml
  config/routes/dev/web_profiler.yaml
  config/services.yaml
  migrations/.gitignore
  phpunit.xml.dist
  public/index.php
  src/Controller/.gitignore
  src/Entity/.gitignore
  src/Kernel.php
  src/Repository/.gitignore
  symfony.lock
  templates/base.html.twig
  tests/bootstrap.php
  translations/.gitignore
Labels: enhancement

#6 Docker & makefile initialization
  .gitignore
  Makefile
  docker-compose.override.yml
  docker-compose.override.yml.dist
  docker-compose.yml
  docker/nginx.conf
  docker/php.Dockerfile
Labels: enhancement

#7 github config
  .github/ISSUE_TEMPLATE/config.yml
Labels: documentation

#11 [Add] networks into docker-compose file in order matching best practices
  docker-compose.yml
Labels: documentation, enhancement

#17 Feature/add alicebundle fixtures fixed
  Makefile
  src/composer.json
  src/composer.lock
  src/config/bundles.php
  src/config/packages/dev/hautelook_alice.yaml
  src/config/packages/dev/nelmio_alice.yaml
  src/config/packages/test/hautelook_alice.yaml
  src/config/packages/test/nelmio_alice.yaml
  src/fixtures/.gitignore
  src/fixtures/project.yaml
  src/fixtures/question.yaml
  src/fixtures/star.yaml
  src/fixtures/user.yaml
  src/fixtures/vote.yaml
  src/src/Entity/MappedSuperclassBase.php
  src/symfony.lock
Labels: enhancement

#23 [Update] class files & [Fix] class representation into the DB
  Makefile
  app/src/Entity/Base.php
  app/src/Entity/Project.php
  app/src/Entity/Question.php
  app/src/Entity/Star.php
  app/src/Entity/User.php
  app/src/Entity/Vote.php
  app/src/Repository/BaseRepository.php
Labels: enhancement

#24 Feature/add frontend design
  app/public/assets/imgs/discord-bg-1.jpg
  app/public/assets/imgs/discord-bg-2.png
  app/src/Controller/HomeController.php
  app/src/Controller/LoginController.php
  app/templates/base.html.twig
  app/templates/home/index.html.twig
  app/templates/login/index.html.twig
Labels: enhancement, front-end
